apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-gpu-exporter
spec:
  selector:
    matchLabels:
      app: node-gpu-exporter
  template:
    metadata:
      labels:
        app: node-gpu-exporter
    spec:
      imagePullSecrets:
        - name: aliyun-registry-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nenly.cn/accelerator-gpu
                operator: Exists
      hostPID: true
      containers:
      - name: node-gpu-exporter
        image: registry.cn-beijing.aliyuncs.com/nenly/pod-gpu-exporter:0716
        imagePullPolicy: Always
        ports:
        - containerPort: 9445
          hostPort: 9445
        resources:
          requests:
            memory: 100Mi 	
            cpu: 100m
          limits:
            memory: 150Mi
            cpu: 200m
